- name: deploy nmos registry and node implementation
  k8s:
    state: present
    src: "{{ item }}"
  loop:
    - ./src/deployment/nmos-registry.yml
    - ./src/deployment/nmos-node.yml

- name: deploy amwa nmos testing 
  k8s:
    state: present
    src: ./src/deployment/nmos-testing.yml

- name: deploy nmos services
  k8s:
    state: present
    src: "{{ item }}"
  loop:
    - ./src/service/nmos-registry-svc.yml
    - ./src/service/nmos-node-svc.yml
    - ./src/service/nmos-testing-svc.yml