apiVersion: v1
kind: Service
metadata:
  name: nmos-registry
  namespace: nmos-dev
spec:
  ports:
  - nodePort: 30011
    port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    app: nmos-registry
  sessionAffinity: None
  type: NodePort

