apiVersion: v1
kind: Service
metadata:
  name: nmos-node
  namespace: nmos-dev
spec:
  ports:
  - nodePort: 30012
    port: 11000
    protocol: TCP
    targetPort: 11000
  selector:
    app: nmos-node
  sessionAffinity: None
  type: NodePort
