apiVersion: v1
kind: Service
metadata:
  name: nmos-testing
  namespace: nmos-dev
spec:
  ports:
  - nodePort: 30010
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: nmos-testing
  sessionAffinity: None
  type: NodePort